# Generated by Django 4.2 on 2023-05-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('img', models.ImageField(blank=True, null=True, upload_to='moviez/img')),
            ],
        ),
    ]
